service: demo-env-slackbot

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  push:
    handler: githubPush.post
    events:
      - http:
          path: push
          method: post
          request:
            parameters:
              headers:
                x-hub-signature: true
